language: php
dist: trusty
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm
        - before_script:
            - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
    - hhvm-nightly
        - before_script:
            - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

matrix:
    include:
        - php: 5.3
          dist: precise

script: phpunit --verbose
