language: php
dist: precise
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - hhvm-nightly

matrix:
    include:
        - php: 'hhvm'
          dist: trusty
    allow_failures:
        - php: 7.0
        - php: 7.1
        - php: hhvm-nightly

script: phpunit --verbose
