language: php
dist: trusty
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - hhvm-nightly

matrix:
    include:
        - php: 5.3
          dist: precise

script: phpunit --verbose
