language: php
dist: precise
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

matrix:
    include:
        - php: hhvm
          dist: trusty
        - php: hhvm-nightly
          dist: trusty
    allow_failures:
        - php: 7.0
        - php: 7.1

script: phpunit --verbose
